### PR TITLE
Add deposit ether command

### PR DESCRIPTION
**Pull request by syuhei176**
## How it works

Copy .env.example to `.env`.
Add MNEMONICS and ROOTCHAIN_ENDPOINT to `.env` file.

In packages/contracts, use command below. It takes 0.1 ether.

```
node src/index.js deposit
```

### Result

screen shot 2018-08-21 at 11 42 22

### CODE REVIEW

**Comment by syuhei176** [comment]
Update `get-balance` command to get weth and eth of child chain.

**Comment by jdkanani** [comment]
wow!

**Comment by shogochiai** [comment]
gen, deposit, get-balance were working fine!

screen shot 2018-08-23 at 16 42 33

**Comment by jdkanani** [comment]
Good to see dev tools on top of Matic! 👍

**Pull request merged**
