### PR TITLE
[WIP] crypto and stream package's compatibility testing

### PR DESCRIPTION
**Pull request by shogochiai**
Just following to this article
https://github.com/philikon/ReactNativify

### CODE REVIEW

**Comment by shogochiai** [comment]
`transformer.js` is not loaded hence `stream` is not replaced with  `stream-browserify`.

Oddly `crypto` is replaced with package.json's `react-native` field by react-native

**Comment by shogochiai** [comment]
This line triggers babel transformer
https://github.com/cryptoeconomicslab/automatic/pull/12/files#diff-e48aa8647b5cb0e275a33e5b58d4b0f3R70

**Comment by shogochiai** [comment]
xdl(expo-development-library)'s latest version is `50.7.0`
https://github.com/expo/xdl/blob/master/CHANGELOG.md


But error says we are using `50.8.0`
screen shot 2018-08-18 at 9 27 16

Line  1332 doesn't have reported code
https://github.com/expo/xdl/blob/master/src/Project.js#L1332

**Comment by shogochiai** [comment]
As per that Project.js, `rn-cli.config.js` resolution related at least. But name resolution has been seemed for me to be succeeded.

**Comment by syuhei176** [comment]
https://github.com/react-community/create-react-native-app/blob/master/CONTRIBUTING.md#working-on-dependencies-of-react-native-scripts


like this?

```
{
  "expo": {
    "name": "app",
    "description": "A very interesting project.",
    "packagerOpts": {
      "config": "./rn-cli.config.js"
    },
...
}

```

**Comment by shogochiai** [comment]
@syuhei176 Your point was correct. 

And next this: `jest-haste-map` says `watchman` isn't running.
https://forums.expo.io/t/jest-haste-map-watchman-crawl-failed/3820/3

**Comment by shogochiai** [comment]
After I run `brew install watchman` then former error has gone.

But `expo start` start hanging up without any error.

**Comment by shogochiai** [comment]
- `npm i -g react-native-cli`
- `react-native start`

These above could you me the usual `Metro Bundler ready.` message.

But hangs up on `Loading dependency graph...` message.

**Comment by shogochiai** [comment]
Watchman issue

```
Loading dependency graph...2018-08-18T18:03:26,282: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/sg-state/sock! (No such file or directory)

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-08-18T18:03:26,282: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/sg-state/sock! (No such file or directory)
```

**Comment by shogochiai** [comment]
Currently `watchman -v: 4.9.4`

**Comment by shogochiai** [comment]
`sudo watchman -f --logfile=/tmp/watchman-automatic.log --log-level=2  --sockname=sock`
`sudo tail -f /tmp/watchman-automatic.log`
`node node_modules/react-native/local-cli/cli.js start`

**Comment by syuhei176** [comment]
`expo start` don't work?

```
[21:21:57] Starting project at /Users/syuhei/work/automatic/packages/app
[21:22:03] jest-haste-map: the `ignorePattern` options as a function is being deprecated. Provide a RegExp instead. See https://github.com/facebook/jest/pull/4063.
[21:22:03] Starting Metro Bundler on port 19001.
[21:22:03] Metro Bundler ready.
[21:22:03] jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
[21:22:03]   Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
[21:22:03]   TypeError: ignorePattern is not a function
[21:22:05] Metro Bundler failed to start. (code: undefined)
```

**Comment by shogochiai** [comment]
Maybe we'd better to search where is causing `TypeError: ignorePattern is not a function` msg.

**Comment by syuhei176** [comment]
https://github.com/facebook/jest/blob/master/types/HasteMap.js#L20
https://github.com/facebook/jest/blob/ede0fe364da88c6e72871445362467beccb6e833/packages/jest-haste-map/src/index.js#L55

ignorePattern's type is `HasteRegExp`. And HasteRegExp can be regexp or function... This is problem.

**Comment by shogochiai** [comment]
These two lines must validate both "RegExp" and "HasteRegExp" maybe. I will make monkeypatch

https://github.com/facebook/jest/blob/ede0fe364da88c6e72871445362467beccb6e833/packages/jest-haste-map/src/index.js#L243

https://github.com/facebook/jest/blob/ede0fe364da88c6e72871445362467beccb6e833/packages/jest-haste-map/src/index.js#L906

**Comment by shogochiai** [comment]
```
 * The HasteMap is created as follows:
 *  1. read data from the cache or create an empty structure.
 *
 *  2. crawl the file system.
 *     * empty cache: crawl the entire file system.
 *     * cache available:
 *       * if watchman is available: get file system delta changes.
 *       * if watchman is unavailable: crawl the entire file system.
 *     * build metadata objects for every file. This builds the `files` part of
 *       the `HasteMap`.
 *
 *  3. parse and extract metadata from changed files.
 *     * this is done in parallel over worker processes to improve performance.
 *     * the worst case is to parse all files.
 *     * the best case is no file system access and retrieving all data from
 *       the cache.
 *     * the average case is a small number of changed files.
 *
 *  4. serialize the new `HasteMap` in a cache file.
 *     Worker processes can directly access the cache through `HasteMap.read()`.
```

**Comment by shogochiai** [comment]
I believe `HasteRegExp` is flowtype's  naming. And actual runtime-type is `HashMap`

**Comment by syuhei176** [comment]
called from https://github.com/facebook/metro/blob/v0.43.5/packages/metro/src/node-haste/DependencyGraph.js#L100

**Comment by shogochiai** [comment]
OMG, `rn-cli.config.js`'s blacklist config is the matter. `return []` is not empty. `return false` is better. I fixed it and works fine.

**Comment by shogochiai** [comment]
Now `tansformer.js`'s `transform` function is not called.

**Comment by syuhei176** [comment]
thanks!

I try to edit transfomer

```
module.exports.transform = function(data) {
  return transform(data.sourceCode, data.filename, data.options);
};
```

**Comment by shogochiai** [comment]
Maybe this solves
https://github.com/philikon/ReactNativify/issues/6#issuecomment-306072846

**Comment by shogochiai** [comment]
`crypto-browserify` or `react-native-crypto`?

Anyway I try.
https://github.com/wswoodruff/strangeluv-native/blob/fa6c260ef0b2f3ad4400c27d075649ecd9bb71b8/config/babel-transformer.js#L21

**Comment by shogochiai** [comment]
Almost 100% sure transform function is called because the error msg is reactive for "binary search"-like code replacement. But the matter is "The error msg is being squashed by expo/AppEntry.js"-phenomenon. Some sort of debugger/debugging-method is needed.


screen shot 2018-08-19 at 10 12 05

**Comment by Hiro359** [comment]
1. We confirmed that `node_modules/metro/src/JSTransformer/index.js#L101`'s `code` variable is exactly same text with `node_modules/expo/AppEntry.js`

2. I and sg made `node_modules/expo/AppEntry.js` empty. Then we did `npm start` again. But the error is still keep same with https://github.com/cryptoeconomicslab/automatic/pull/12#issuecomment-414096141

3. So conclusion is: `node_modules/expo/AppEntry.js` and `automatic/packages/app/App.js` aren't the cause of this bug at all.

**Comment by Hiro359** [comment]
`babel-core/lib/transformation/file/index.js`'s `parse()` function uses `babylon` module.

This module failed to parse the input `code` argument.

This `code` is `"[Object object]"` string. So input validation issue causes this complicated error.

Next action will be transform input sanitization and malformed input causing line clarification.

**Comment by shogochiai** [comment]
We could narrow down the issue. So make another branch for finish work

**Pull request merged**
