### PR TITLE
Proposal: separate cli.js and index.js to make library

### PR DESCRIPTION
**Pull request by syuhei176**
Proposal. We wanna use deposit and getBalance from other dapps(ex expo app).
So I separated cli.js for CLI and index.js for SDK.
And change name `automatic-sdk`.
@shogochiai 

We wanna use sdk like this.

```js
const { deposit } = require("automatic-sdk")
let context = {.../*web3, wallet, chainaddress, ...etc*/}

const result = await deposit(context, "0.1")
```

### CODE REVIEW

**Comment by shogochiai** [comment]
I think this can be simply `matic-sdk.js` @jdkanani

**Comment by jdkanani** [comment]
Yeah. We have also planned for it :) I was thinking to write a small wrapper on ethers.js!

Most pieces are already in place "matic-demo" repository in gitlab. Just need to collect from there to `matic.js`. Let me setup repository at github.com/maticnetwork, so you don't have to create new sdk. That will also reduce redundancy.

**Comment by jdkanani** [comment]
We will also use `matic.js` in our upcoming app.

**Comment by jdkanani** [comment]
Just created https://github.com/maticnetwork/matic.js 

I will setup like lint/jenkins/build etc soon.

**Comment by shogochiai** [comment]
I guess automatic's responsibility would be `swiss army knife for the person who try to build forked matic`. So `maticnetwork/matic.js` would be for the person who simply rely on Matic core. For now this pull-request is duplicating with `maticnetwork/matic.js` but this repo will differ due to customizability.

And I would like to emphasize `maticnetwork/matic.js` had better to be simply and straight forward.

**Comment by shogochiai** [comment]
I dare want to add

```
- Multi chain management cli
- Checkpoint nodes management cli
- Delegate management cli
- Economic constant management cli for each chain
- And so more for "deepdive" usage
```

**Comment by syuhei176** [comment]
@jdkanani @shogochiai Ok, thanks. So we can depend on https://github.com/maticnetwork/matic.js, for cli(`deposit' and `withdraw`).

**Pull request closed without merging**
